# Generated by Django 5.2.5 on 2025-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_account_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='_default_address',
            new_name='default_address',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
