# Generated by Django 5.2.5 on 2025-08-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeditem',
            name='customer',
        ),
    ]
