# Generated by Django 5.2.5 on 2025-08-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='featured_product',
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
    ]
