# Generated by Django 5.2.5 on 2025-08-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_brand_slug_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='http://dummyimage.com/209x100.png/cc0000/ffffff', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='catalog.promotion'),
        ),
    ]
