# Generated by Django 5.2.5 on 2025-08-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_images_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default='summer-sale'),
            preserve_default=False,
        ),
    ]
