# Generated by Django 5.2.5 on 2025-08-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_promotion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
