# Generated by Django 5.2.5 on 2025-08-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
